/* eslint-disable react-hooks/immutability, react-hooks/static-components, react-hooks/exhaustive-deps */
"use client";

import { useCallback, useEffect, useRef, useState } from "react";

type Scene = "title" | "opening" | "game" | "ending";
type Dir = "up" | "down" | "left" | "right";
type Floor = "1F"|"2F"|"B1F"|"B2F"|"B3F";
type Flag = "note"|"diary2"|"diary3"|"diary4"|"key"|"red"|"yellow"|"blue"|"solvent"|"puzzle"|"clue"|"burned"|"chase";
type SaveData = { x:number; y:number; flags:Flag[]; chapter:number; sanity?:number; battery?:number; floor?:Floor };

const W=768, H=432;
const SAVE_KEY="rainbow-atelier-save-v1";
const dialogues: Record<string,string[]> = {
  intro:["유나: 오늘도 원장님 수업은 참 따뜻해.","…그런데, 복도에서 기름 냄새가 나.","[조작] 방향키/WASD 이동 · Z/Space 조사 · Shift 달리기"],
  note:["『아이들이 두려움은 정맥의 푸른빛을 더욱 깊게 만든다.』","유나: 이건… 원장님의 글씨야."],
  locked:["지하 문이다. 세 개의 안료 홈이 비어 있다.","붉은색 물감을 먼저 찾아야 할 것 같다."],
  red:["동맥의 붉은색 물감 튜브를 얻었다.","손끝에 닿자 미지근한 맥박이 느껴진다."],
  puzzle:["R · G · B 안료가 하나의 회색으로 가라앉는다.","철컥. 지하 2층으로 향하는 문이 열렸다."],
  clue:["낡은 작업대 아래에서 붉은 머리끈을 발견했다.","유나: 유진이 거야… 동생은 분명 여기까지 왔었어.","[TRUE CLUE] 엔딩의 진실에 한 걸음 가까워졌다."],
  key:["원장실 액자 뒤에서 청동 열쇠를 찾았다.","[BRONZE BASEMENT KEY] 지하 1층 출입문을 열 수 있다."],
  seoa:["핏빛 캔버스 속 얼굴이 눈을 떴다.","서아: …유…나… 도…망…쳐…", "핏빛 붉은 안료와 뇌척수액 푸른 안료를 회수했다."],
  craft:["두 안료가 부글거리며 주황빛 용제로 변했다.","[ORANGE SOLVENT] B2F의 부식된 철문을 녹일 수 있다."],
  memory:["유진: 언니가 나를 원장님에게 데려왔잖아.","유나: 아니야… 난 그저 네 재능을 보여주고 싶었어…", "봉인했던 기억이 돌아온다. 증류소를 불태워야 한다."],
  minhyuk:["민혁: 유나야… 손에 왜 그래? 피가… 피가 안 멈추잖아!","유나: 선배, 이건 피가 아니라 ‘황금빛 노란색’이야.","민혁: 다음은 네 차례야. 네 안에는 아주 깊은 푸른 슬픔이 있거든…"],
  escape:["차가운 새벽 공기가 폐 안으로 들어온다.","하지만 학원 지하에서는 아직도 붓 긁는 소리가 난다."],
};

function useAudio(){
  const ctx=useRef<AudioContext|null>(null);
  return useCallback((kind:"step"|"pickup"|"shock")=>{
    try { const C=window.AudioContext || (window as typeof window & {webkitAudioContext:typeof AudioContext}).webkitAudioContext; const c=ctx.current??new C(); ctx.current=c; const o=c.createOscillator(), g=c.createGain(); o.connect(g);g.connect(c.destination); const now=c.currentTime; o.type=kind==="shock"?"sawtooth":"square"; o.frequency.setValueAtTime(kind==="step"?90:kind==="pickup"?480:55,now); if(kind==="shock")o.frequency.exponentialRampToValueAtTime(620,now+.35); g.gain.setValueAtTime(.05,now);g.gain.exponentialRampToValueAtTime(.001,now+(kind==="shock"?.45:.08));o.start(now);o.stop(now+(kind==="shock"?.46:.09)); } catch {}
  },[]);
}

export default function RainbowAtelier(){
  const canvas=useRef<HTMLCanvasElement>(null); const keys=useRef(new Set<string>()); const player=useRef({x:102,y:306,dir:"down" as Dir}); const enemy=useRef({x:650,y:90});
  const [scene,setScene]=useState<Scene>("title"),[dialog,setDialog]=useState<string[]>([]),[line,setLine]=useState(0),[flags,setFlags]=useState<Flag[]>([]),[floor,setFloor]=useState<Floor>("1F"),[chapter,setChapter]=useState(1),[stamina,setStamina]=useState(100),[sanity,setSanity]=useState(100),[battery,setBattery]=useState(100),[light,setLight]=useState(true),[inventory,setInventory]=useState(false),[paused,setPaused]=useState(false),[mixing,setMixing]=useState(false),[hiding,setHiding]=useState(false),[flash,setFlash]=useState(false),[hasSave,setHasSave]=useState(()=>typeof window!=="undefined"&&!!localStorage.getItem(SAVE_KEY)),[ending,setEnding]=useState<"normal"|"bad"|"true">("normal");
  const beep=useAudio(); const flagsRef=useRef(flags); const floorRef=useRef(floor); const dialogRef=useRef(dialog); const staminaRef=useRef(stamina); const sanityRef=useRef(sanity); const batteryRef=useRef(battery); const chapterRef=useRef(chapter); const last=useRef(0);
  useEffect(()=>{flagsRef.current=flags},[flags]);useEffect(()=>{floorRef.current=floor},[floor]);useEffect(()=>{dialogRef.current=dialog},[dialog]);useEffect(()=>{staminaRef.current=stamina},[stamina]);useEffect(()=>{sanityRef.current=sanity},[sanity]);useEffect(()=>{batteryRef.current=battery},[battery]);useEffect(()=>{chapterRef.current=chapter},[chapter]);
  const speak=useCallback((lines:string[])=>{setDialog(lines);setLine(0)},[]);
  const addFlag=useCallback((f:Flag)=>setFlags(v=>v.includes(f)?v:[...v,f]),[]);
  const save=useCallback(()=>{localStorage.setItem(SAVE_KEY,JSON.stringify({x:player.current.x,y:player.current.y,flags:flagsRef.current,chapter:chapterRef.current,sanity:sanityRef.current,battery:batteryRef.current,floor:floorRef.current} satisfies SaveData));setHasSave(true);beep("pickup")},[beep]);
  const start=useCallback((load=false)=>{if(load){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY)||"") as SaveData;player.current.x=s.x;player.current.y=s.y;setFlags(s.flags);setChapter(s.chapter);setSanity(s.sanity??100);setBattery(s.battery??100);setFloor(s.floor??"1F")}catch{}setScene("game")} else {player.current={x:102,y:306,dir:"down"};setFlags([]);setFloor("1F");setChapter(1);setSanity(100);setBattery(100);setScene("opening")}},[]);

  const warp=useCallback((next:Floor,x=105,y=305)=>{setFloor(next);player.current={x,y,dir:"down"};enemy.current={x:650,y:90}},[]);
  const interact=useCallback(()=>{
    if(dialogRef.current.length){if(line<dialogRef.current.length-1)setLine(v=>v+1);else setDialog([]);return}
    const {x,y}=player.current,f=flagsRef.current,fl=floorRef.current;
    if(fl==="1F"){
      if(x<180&&y<165&&!f.includes("note")){addFlag("note");speak(["[일기 1/4] 실종 학생들은 모두 ‘색채 적성’ 검사를 받았다.",...dialogues.note]);beep("pickup")}
      else if(x>585&&y<165&&!f.includes("key")){addFlag("key");speak(dialogues.key);beep("pickup")}
      else if(x>300&&x<500&&y<165)warp("2F",105,305)
      else if(x>610&&y>280){if(f.includes("key"))warp("B1F");else speak(["청동 자물쇠가 걸려 있다. 원장실을 수색해야 한다."])}
    }else if(fl==="2F"){
      if(x<180&&y<165&&!f.includes("diary2")){addFlag("diary2");speak(["[일기 2/4] 빨강은 피, 노랑은 담즙, 파랑은 뇌척수액. 원장은 인간을 안료로 분류했다."]);beep("pickup")}
      else if(x>585&&y<165&&!f.includes("yellow")){addFlag("yellow");speak(["직원실 냉장고에서 담즙의 노란 안료를 얻었다."]);beep("pickup")}
      else if(x<110&&y>280)warp("1F",380,185)
    }else if(fl==="B1F"){
      if(x<180&&y<165&&!f.includes("red")){addFlag("red");speak(dialogues.red);beep("pickup")}
      else if(x>585&&y<165&&!f.includes("blue")){addFlag("blue");speak(["깨진 배양조에서 뇌척수액의 푸른 안료를 회수했다."]);beep("pickup")}
      else if(x>610&&y>280&&!f.includes("puzzle")){if(f.includes("red")&&f.includes("yellow")&&f.includes("blue"))setMixing(true);else speak(["배합기에 R·G·B 안료가 모두 필요하다. 2F 직원실도 확인해 보자."])}
      else if(x>300&&x<500&&y<165&&f.includes("puzzle")){setFlash(true);setSanity(v=>Math.max(0,v-22));beep("shock");speak(dialogues.seoa);setChapter(2);setTimeout(()=>{setFlash(false);warp("B2F");addFlag("chase")},1300)}
      else if(x<110&&y>280)warp("1F",630,270)
    }else if(fl==="B2F"){
      if(x<180&&y<165&&!f.includes("diary3")){addFlag("diary3");speak(["[일기 3/4] 민혁은 살기 위해 학생들의 귀가 시간을 원장에게 넘겼다.",...dialogues.minhyuk]);beep("pickup")}
      else if(x>585&&y<165){setHiding(true);beep("pickup")}
      else if(x>610&&y>280){if(f.includes("solvent")){setChapter(3);warp("B3F")}else speak(["부식된 철문이 붙어 움직이지 않는다.","가방에서 붉은 안료와 노란 안료를 조합해 보자."])}
    }else if(fl==="B3F"){
      if(x<180&&y<165&&!f.includes("clue")){addFlag("clue");speak(dialogues.clue);beep("pickup")}
      else if(x>300&&x<500&&y<165&&!f.includes("diary4")){addFlag("diary4");speak(["[일기 4/4] 유진은 일곱 번째 안료가 아니었다. 원장을 멈출 유일한 기억의 닻이었다.",...dialogues.memory]);beep("pickup")}
      else if(x>585&&y<165&&!f.includes("burned")){addFlag("burned");addFlag("chase");enemy.current={x:70,y:80};setChapter(4);setSanity(v=>Math.max(0,v-20));setFlash(true);beep("shock");speak(["라이터 불꽃이 증류소로 번진다.","클렘: 내 색을 망치지 마!", "불길을 피해 1층 출구로 달려가야 한다!"]);setTimeout(()=>setFlash(false),700)}
      else if(x<110&&y>280&&f.includes("burned")){const diaries=["note","diary2","diary3","diary4"].filter(d=>f.includes(d as Flag)).length;setEnding(f.includes("clue")&&diaries===4?"true":"normal");setScene("ending")}
    }
  },[addFlag,beep,line,speak,warp]);

  useEffect(()=>{const down=(e:KeyboardEvent)=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();keys.current.add(e.key.toLowerCase());if(e.key===" "||e.key.toLowerCase()==="z")interact();if(e.key.toLowerCase()==="f")setLight(v=>!v);if(e.key.toLowerCase()==="i"||e.key==="Tab"){e.preventDefault();setInventory(v=>!v)}if(e.key==="Escape")setPaused(v=>!v)};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[interact]);

  useEffect(()=>{if(scene!=="game")return;let raf=0;const loop=(t:number)=>{const dt=Math.min((t-last.current)/16.67,2);last.current=t;const k=keys.current,p=player.current;const running=(k.has("shift"))&&staminaRef.current>0;const speed=(running?3.4:2.05)*dt;if(!paused&&!inventory&&!mixing&&!hiding&&!dialogRef.current.length){let dx=0,dy=0;if(k.has("arrowleft")||k.has("a")){dx=-speed;p.dir="left"}if(k.has("arrowright")||k.has("d")){dx=speed;p.dir="right"}if(k.has("arrowup")||k.has("w")){dy=-speed;p.dir="up"}if(k.has("arrowdown")||k.has("s")){dy=speed;p.dir="down"}p.x=Math.max(55,Math.min(W-48,p.x+dx));p.y=Math.max(62,Math.min(H-43,p.y+dy));setStamina(v=>Math.max(0,Math.min(100,v+(running&&(dx||dy)?-.45:.28)*dt)));if(light&&batteryRef.current>0){setBattery(v=>Math.max(0,v-.012*dt));if(batteryRef.current<.2)setLight(false)}if(floorRef.current==="B2F"||flagsRef.current.includes("burned")){setSanity(v=>Math.max(0,v-.018*dt));const e=enemy.current,ang=Math.atan2(p.y-e.y,p.x-e.x);e.x+=Math.cos(ang)*1.35*dt;e.y+=Math.sin(ang)*1.35*dt;if(Math.hypot(p.x-e.x,p.y-e.y)<25||sanityRef.current<=0){setEnding("bad");setScene("ending");beep("shock")}}}draw();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[scene,paused,inventory,mixing,hiding,light,beep]);

  const draw=useCallback(()=>{const c=canvas.current;if(!c)return;const x=c.getContext("2d")!;x.imageSmoothingEnabled=false;const fl=floorRef.current;const horror=fl==="B2F"||flagsRef.current.includes("burned");x.fillStyle=horror?"#09050b":"#1a2030";x.fillRect(0,0,W,H);x.fillStyle=horror?"#211015":"#d6b67e";x.fillRect(36,42,W-72,H-74);for(let yy=56;yy<H-45;yy+=32)for(let xx=50;xx<W-50;xx+=32){x.fillStyle=(xx/32+yy/32)%2? (horror?"#3a1a20":"#debF89"):(horror?"#2c1319":"#c8a470");x.fillRect(xx,yy,29,29)}x.fillStyle="#443346";x.fillRect(36,36,W-72,24);x.fillRect(36,H-42,W-72,12);x.fillStyle="#6a3b3d";x.fillRect(286,76,196,75);x.fillStyle="#c99b5a";x.fillRect(304,91,50,44);x.fillRect(377,91,86,44);x.fillStyle="#263440";x.fillRect(50,78,125,72);x.fillStyle="#8a714b";for(let i=0;i<3;i++)x.fillRect(60+i*36,91,24,42);x.fillStyle="#342a40";x.fillRect(596,74,122,78);x.fillStyle="#a52d43";x.fillRect(610,91,92,13);x.fillStyle="#1e1722";x.fillRect(620,109,72,29);x.fillStyle="#222536";x.fillRect(614,278,104,100);x.fillStyle="#7d5b3e";x.fillRect(630,292,72,72);x.fillStyle="#ddb81d";x.fillRect(662,328,8,8);x.fillStyle="#1d2029";x.fillRect(36,282,24,95);x.fillStyle="#eee2c5";x.font="bold 12px monospace";x.fillText("EXIT",31,275);x.fillStyle="#f7e8c8";x.font="bold 18px monospace";x.fillText(fl,68,86);x.font="bold 10px monospace";const labels:Record<Floor,[string,string,string]>= {"1F":["일기","2F 계단","원장실"],"2F":["일기","1F 계단","직원실"],"B1F":["붉은 안료","서아 캔버스","푸른 안료"],"B2F":["민혁의 일기","구금실","캐비닛"],"B3F":["유진 머리끈","기억의 제단","증류소"]};x.fillText(labels[fl][0],68,116);x.fillText(labels[fl][1],340,116);x.fillText(labels[fl][2],618,116);
    const p=player.current;x.fillStyle="#5c376c";x.fillRect(p.x-8,p.y-11,16,19);x.fillStyle="#dfb09c";x.fillRect(p.x-7,p.y-18,14,9);x.fillStyle="#322231";x.fillRect(p.x-8,p.y-20,16,5);x.fillStyle="#fff";x.fillRect(p.x-4,p.y-16,2,2);x.fillRect(p.x+3,p.y-16,2,2);x.fillStyle="#28203a";x.fillRect(p.x-8,p.y+8,6,6);x.fillRect(p.x+2,p.y+8,6,6);
    if(horror){const e=enemy.current;x.fillStyle="#19111b";x.fillRect(e.x-11,e.y-15,22,28);x.fillStyle="#e3d2c4";x.fillRect(e.x-9,e.y-23,18,12);x.fillStyle="#d91f3c";x.fillRect(e.x-5,e.y-19,3,3);x.fillRect(e.x+3,e.y-19,3,3);x.fillStyle="rgba(160,0,20,.15)";x.fillRect(0,0,W,H)}
    if(light&&batteryRef.current>0){const radius=batteryRef.current<20?105+Math.random()*24:150;const g=x.createRadialGradient(p.x,p.y,20,p.x,p.y,radius);g.addColorStop(0,"rgba(255,244,192,.08)");g.addColorStop(.55,"rgba(0,0,0,.28)");g.addColorStop(1,"rgba(0,0,0,.92)");x.fillStyle=g;x.fillRect(0,0,W,H)}else{x.fillStyle="rgba(0,0,0,.82)";x.fillRect(0,0,W,H)}
  },[light]);

  const moveTouch=(d:Dir,on:boolean)=>{const key={up:"w",down:"s",left:"a",right:"d"}[d];if(on)keys.current.add(key);else keys.current.delete(key)};
  if(scene==="title")return <TitleScreen onStart={()=>start(false)} onLoad={()=>start(true)} hasSave={hasSave}/>;
  if(scene==="opening")return <OpeningCutscene onComplete={()=>{setScene("game");speak(["[메인 목표] 열려 있는 쪽문으로 진입하세요.","1층 원장실을 수색하고 지하로 내려가는 열쇠를 확보하세요.","[조작] 방향키/WASD 이동 · Z/Space 조사 · F 손전등"])}}/>;
  if(scene==="ending")return <Ending kind={ending} onAgain={()=>{enemy.current={x:650,y:90};start(false)}}/>;
  const diaries=["note","diary2","diary3","diary4"].filter(d=>flags.includes(d as Flag)).length;
  const objective=floor==="1F"?(!flags.includes("key")?"원장실에서 청동 지하 열쇠 찾기":"B1F 출입문 또는 2F 조사"):floor==="2F"?"직원실의 노란 안료와 일기 수색":floor==="B1F"?(!flags.includes("puzzle")?"세 안료를 모아 RGB 배합기 가동":"서아의 캔버스를 조사"):floor==="B2F"?(!flags.includes("solvent")?"가방에서 오렌지 용제 조합":"부식된 철문을 녹이고 B3F로 이동"):!flags.includes("burned")?`기억 수집 ${diaries}/4 · 머리끈 · 증류소 조사`:"불타는 증류소에서 출구로 탈출!";
  const distorted=sanity<40;
  return <main className={`min-h-screen bg-[#090b17] px-3 py-5 lg:px-8 ${distorted?"glitch":""}`}><div className="mx-auto max-w-[1180px]"><header className="mb-4 flex items-end justify-between gap-4"><div><p className="text-[10px] tracking-[.35em] text-rose-400">THE RAINBOW ATELIER</p><h1 className="mt-1 text-xl font-black sm:text-2xl">무지개빛 미술학원</h1></div><div className="text-right text-xs text-slate-400">CHAPTER {chapter} · {floor} · 일기 {diaries}/4<br/><span className="text-amber-300">{distorted?"누가 내 붓으로 너를 그리고 있어…":objective}</span></div></header><section className={`relative overflow-hidden border-4 border-[#272b42] bg-black shadow-2xl crt ${flash?"glitch":""}`}><canvas ref={canvas} width={W} height={H} className="pixel block aspect-video w-full" aria-label="무지개빛 미술학원 게임 화면"/><div className="absolute left-3 top-3 z-20 flex gap-2"><Hud label="STAMINA" value={stamina}/><Hud label="SANITY" value={sanity} danger/><Hud label="BATTERY" value={battery} danger/><button onClick={()=>setLight(v=>!v)} className="border border-white/20 bg-black/65 px-2 text-xs">{light?"◉ LIGHT":"○ DARK"}</button></div>{(floor==="B2F"||flags.includes("burned"))&&<div className="pointer-events-none absolute inset-x-0 top-4 z-20 text-center text-sm font-black tracking-[.35em] text-red-500">RUN · 캐비닛에서 숨을 수 있다</div>}{dialog.length>0&&<button onClick={interact} className="absolute inset-x-4 bottom-4 z-40 min-h-24 border-2 border-[#e9d9b8] bg-[#0e1020]/95 flex items-center gap-4 p-4 text-left text-sm leading-7 shadow-[6px_6px_0_#111] sm:text-base"><Portrait mood={sanity<30?"insane":(floor==="B2F"||flags.includes("burned"))?"terrified":sanity<70?"suspicious":"neutral"}/><span className="flex-1">{dialog[line]}</span><span className="float absolute bottom-2 right-3 text-amber-300">▼</span></button>}{inventory&&<Inventory flags={flags} sanity={sanity} craft={()=>{if(flags.includes("red")&&flags.includes("yellow")&&!flags.includes("solvent")){addFlag("solvent");setInventory(false);speak(dialogues.craft);beep("pickup")}}} close={()=>setInventory(false)}/>} {mixing&&<MixingPuzzle close={()=>setMixing(false)} complete={()=>{setMixing(false);addFlag("puzzle");setChapter(2);speak(dialogues.puzzle);beep("pickup")}}/>}{hiding&&<HideQTE done={(success)=>{setHiding(false);if(success){enemy.current={x:80,y:340};setSanity(v=>Math.min(100,v+12))}else{setSanity(v=>Math.max(0,v-25));beep("shock")}}}/>}{paused&&<Pause save={save} close={()=>setPaused(false)} quit={()=>setScene("title")}/>}</section><footer className="mt-4 grid gap-3 text-xs text-slate-400 md:grid-cols-[1fr_auto]"><p>방향키 / WASD 이동 · Shift 달리기 · Z / Space 조사 · F 손전등 · I / Tab 가방 · ESC 메뉴</p><div className="flex items-center justify-center gap-2 md:hidden"><Dpad move={moveTouch}/><button onPointerDown={interact} className="h-14 w-14 rounded-full border-2 border-rose-400 bg-rose-500/20 font-black text-rose-200">Z</button></div><p className="text-right text-slate-600">ESC 메뉴에서 저장 · 광기 0% 시 BAD ENDING</p></footer></div></main>
}

function Hud({label,value,danger=false}:{label:string,value:number;danger?:boolean}){return <div className="w-24 border border-white/20 bg-black/65 p-1 sm:w-28"><div className="mb-1 text-[8px] tracking-widest">{label} {Math.round(value)}</div><div className="h-1.5 bg-white/10"><div className={`h-full transition-all ${danger&&value<40?"bg-red-500":"bg-amber-300"}`} style={{width:`${value}%`}}/></div></div>}
function Portrait({mood}:{mood:"neutral"|"suspicious"|"terrified"|"insane"}){return <div aria-label={`유나 ${mood} 표정`} className={`relative hidden h-20 w-20 shrink-0 overflow-hidden border-2 bg-[#cddbea] sm:block ${mood==="insane"?"border-red-500 glitch":"border-[#d7c8a7]"}`}><div className="absolute left-4 top-2 h-12 w-12 bg-[#d9ad99] shadow-[0_-9px_0_5px_#8bb5cf]"/><i className={`absolute left-7 top-8 h-2 w-2 bg-[#24202b] ${mood==="terrified"?"scale-150":""}`}/><i className={`absolute right-7 top-8 h-2 w-2 bg-[#24202b] ${mood==="terrified"?"scale-150":""}`}/><b className={`absolute left-[34px] top-12 h-1 w-3 bg-[#7b3742] ${mood==="neutral"?"":"rotate-12"}`}/>{mood==="insane"&&<span className="absolute inset-0 bg-[repeating-linear-gradient(90deg,transparent_0_8px,#b0002a55_9px_11px)]"/>}</div>}
type CutBeat={scene:number;place:string;speaker:string;text:string;visual:"room"|"tv"|"phone"|"school";tone?:"danger"|"news"};
const openingBeats:CutBeat[]=[
  {scene:1,place:"유나의 방 · 10:09 PM",speaker:"",text:"비 내리는 밤. 창밖의 주황색 가로등만이 작은 방을 희미하게 물들인다.",visual:"room"},
  {scene:1,place:"유나의 방 · 10:09 PM",speaker:"유나",text:"…오늘따라 비가 그치질 않네. 학원 아이들… 다들 잘 들어갔을까?",visual:"room"},
  {scene:2,place:"TV 속보 · 10:10 PM",speaker:"NEWS",text:"[속보] ○○구 일대 고등학생 연쇄 실종… 벌써 3번째",visual:"tv",tone:"news"},
  {scene:2,place:"TV 속보 · 10:10 PM",speaker:"아나운서",text:"지난달 미술학원 수강생 한 모 군에 이어, 어제 저녁 또 한 명의 고등학생이 귀가 도중 흔적도 없이 실종되었습니다.",visual:"tv",tone:"news"},
  {scene:2,place:"TV 속보 · 10:10 PM",speaker:"아나운서",text:"경찰은 인근 CCTV 및 미술학원 일대를 중심으로 수사를 확대하고 있으나…",visual:"tv",tone:"news"},
  {scene:2,place:"유나의 방 · 10:11 PM",speaker:"유나",text:"…또 실종이야? 벌써 세 명째잖아. 다들 우리 학원 아이들이었는데…",visual:"tv"},
  {scene:3,place:"서아 · 10:12 PM",speaker:"서아",text:"유나야… 집에 있어?",visual:"phone",tone:"danger"},
  {scene:3,place:"서아 · 10:12 PM",speaker:"서아",text:"원장님이 지하실 스터디룸에서 완벽한 ‘붉은 물감’을 완성했다고 하셨어…",visual:"phone",tone:"danger"},
  {scene:3,place:"서아 · 10:13 PM",speaker:"서아",text:"근데 이상해… 물감 냄새가 아니라 피 냄새가 나…",visual:"phone",tone:"danger"},
  {scene:3,place:"서아 · 10:13 PM",speaker:"서아",text:"문이 밖에서 잠겼어. 지하실 문이 안 열려… 나 좀 도와줘 유나야!!!",visual:"phone",tone:"danger"},
  {scene:3,place:"통화 연결 실패",speaker:"유나",text:"서아야?! 전화를 안 받아… 대체 원장님이 밤늦게 지하실에서 뭘 하고 계신 거지…!",visual:"phone",tone:"danger"},
  {scene:4,place:"무지개 미술학원 앞 · 10:27 PM",speaker:"",text:"천둥이 밤하늘을 가른다. 불 꺼진 학원의 지하 창문에서만 핏빛 조명이 새어 나온다.",visual:"school"},
  {scene:4,place:"무지개 미술학원 앞 · 10:27 PM",speaker:"유나",text:"정문이 쇠사슬로 잠겨 있어… 하지만 옆 쪽문은 살짝 열려 있네.",visual:"school"},
  {scene:4,place:"무지개 미술학원 앞 · 10:27 PM",speaker:"유나",text:"서아야, 기다려. 내가 지금 들어갈게.",visual:"school"},
];
function OpeningCutscene({onComplete}:{onComplete:()=>void}){const [beat,setBeat]=useState(0),[muted,setMuted]=useState(false);const b=openingBeats[beat];useEffect(()=>{const auto=setTimeout(()=>setBeat(v=>v<openingBeats.length-1?v+1:(onComplete(),v)),7200);return()=>{clearTimeout(auto)}},[beat,onComplete]);useEffect(()=>{if(muted)return;let ctx:AudioContext|undefined,source:AudioBufferSourceNode|undefined,gain:GainNode|undefined;try{ctx=new AudioContext();const frames=ctx.sampleRate*2,buffer=ctx.createBuffer(1,frames,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<frames;i++)data[i]=(Math.random()*2-1)*(.18+.08*Math.sin(i/91));source=ctx.createBufferSource();source.buffer=buffer;source.loop=true;gain=ctx.createGain();gain.gain.value=.09;source.connect(gain).connect(ctx.destination);source.start()}catch{}return()=>{try{source?.stop();ctx?.close()}catch{}}},[muted]);const next=()=>beat<openingBeats.length-1?setBeat(v=>v+1):onComplete();return <main className="relative min-h-screen overflow-hidden bg-black text-[#f7ecd5]" onClick={next} onKeyDown={e=>{if(e.key===" "||e.key==="Enter")next()}} tabIndex={0} autoFocus><CutVisual kind={b.visual} scene={b.scene}/><div className="pointer-events-none absolute inset-0 bg-[linear-gradient(180deg,rgba(0,0,0,.15),rgba(0,0,0,.05)_50%,rgba(0,0,0,.9))]"/><div className="absolute inset-x-0 top-0 z-30 flex items-center justify-between p-4 text-[10px] tracking-[.25em] text-white/55 sm:p-7"><span>OPENING · 비 내리는 밤의 초청장</span><span>SCENE 0{b.scene} · {beat+1}/{openingBeats.length}</span></div><div key={beat} className="cutscene-dialog absolute inset-x-0 bottom-0 z-30 p-4 sm:p-10"><div className="mx-auto max-w-4xl border-t border-white/25 bg-black/65 p-5 backdrop-blur-sm sm:p-7"><p className="mb-3 text-[10px] tracking-[.28em] text-amber-300">{b.place}</p>{b.speaker&&<p className={`mb-2 text-sm font-black ${b.tone==="danger"?"text-red-400":b.tone==="news"?"text-cyan-300":"text-white"}`}>{b.speaker}</p>}<p className={`max-w-3xl text-sm leading-7 sm:text-lg sm:leading-9 ${b.tone==="danger"?"cutscene-type text-red-200":""}`}>{b.text}</p><p className="mt-4 text-right text-[10px] tracking-widest text-white/40">클릭 / SPACE 다음 ▶</p></div></div><div className="absolute right-4 top-12 z-40 flex gap-2 sm:right-7 sm:top-16"><button onClick={e=>{e.stopPropagation();setMuted(v=>!v)}} className="border border-white/20 bg-black/50 px-3 py-2 text-xs">{muted?"음소거 해제":"음소거"}</button><button onClick={e=>{e.stopPropagation();onComplete()}} className="border border-white/20 bg-black/50 px-3 py-2 text-xs">컷씬 건너뛰기</button></div></main>}
function CutVisual({kind,scene}:{kind:CutBeat["visual"];scene:number}){return <div className={`absolute inset-0 pixel cutscene-scene scene-${kind}`}><div className="rain"/><div className="lightning"/>{kind==="room"&&<><div className="window"><i/><i/><i/></div><div className="bed"><span/></div><div className="easel"><i/></div><div className="yuna-pixel"/></>}{kind==="tv"&&<><div className="room-dark"/><div className="tv-set"><div className="tv-static"><b>긴급 속보</b><span>고등학생 연쇄 실종</span></div></div><div className="yuna-pixel worried"/></>}{kind==="phone"&&<><div className="phone"><div className="phone-notch"/><p>절친 ‘서아’</p><i>10:1{scene} PM</i><div className="message">•••</div></div><div className="red-flash"/></>}{kind==="school"&&<><div className="school"><b>무지개 미술학원</b><div className="school-windows"/><div className="basement-glow"/><div className="side-door"/></div><div className="gate">╳ ╳ ╳ ╳ ╳</div><div className="yuna-pixel raincoat"/></>}</div>}
function TitleScreen({onStart,onLoad,hasSave}:{onStart:()=>void;onLoad:()=>void;hasSave:boolean}){return <main className="noise relative flex min-h-screen items-center justify-center overflow-hidden bg-[radial-gradient(circle_at_50%_35%,#35224c_0,#111326_45%,#060812_100%)] p-6"><div className="absolute -left-20 top-16 h-52 w-52 rotate-12 rounded-full bg-rose-500/10 blur-3xl"/><div className="relative z-10 w-full max-w-3xl text-center"><div className="mx-auto mb-8 grid h-24 w-24 rotate-3 grid-cols-3 gap-1 border-4 border-[#f3e6c9] bg-[#eee0c1] p-3 shadow-[10px_10px_0_#57182c]"><i className="bg-red-500"/><i className="bg-amber-300"/><i className="bg-emerald-400"/><i className="bg-cyan-400"/><i className="bg-blue-500"/><i className="bg-violet-500"/><i className="bg-fuchsia-400"/><i className="bg-rose-300"/><i className="bg-slate-900"/></div><p className="mb-3 text-xs tracking-[.55em] text-rose-400">2D PIXEL PSYCHOLOGICAL HORROR</p><h1 className="text-4xl font-black tracking-[-.06em] text-[#fff4d9] drop-shadow-[5px_5px_0_#7e1733] sm:text-7xl">무지개빛<br/>미술학원</h1><p className="mt-4 font-serif text-sm tracking-[.18em] text-slate-400">The Rainbow Atelier</p><p className="mx-auto mt-8 max-w-md text-sm leading-7 text-slate-300">사라진 동생, 일곱 가지 물감, 그리고 밤마다 들리는 젖은 붓 소리.<br/><span className="text-rose-300">예쁜 색은 언제나 좋은 기억에서 만들어질까?</span></p><div className="mt-10 flex flex-col items-center gap-3"><button onClick={onStart} className="pulse-red w-56 border-2 border-rose-400 bg-rose-600 px-7 py-3 font-black tracking-[.25em] hover:bg-rose-500">새 게임</button><button disabled={!hasSave} onClick={onLoad} className="w-56 border border-white/20 bg-white/5 px-7 py-3 text-sm tracking-[.2em] enabled:hover:bg-white/10 disabled:opacity-30">이어하기</button></div></div><span className="absolute bottom-4 text-[10px] tracking-widest text-slate-600">HEADPHONES RECOMMENDED · 만 15세 이상 권장</span></main>}
function Inventory({flags,sanity,craft,close}:{flags:Flag[];sanity:number;craft:()=>void;close:()=>void}){const low=sanity<30;const items=[{f:"key",n:"청동 지하실 열쇠",c:"#b98b45"},{f:"red",n:low?"아직 따뜻한 심장":"핏빛 붉은 안료",c:"#d72e49"},{f:"yellow",n:low?"썩은 담낭":"담즙의 노란 안료",c:"#d4b624"},{f:"blue",n:low?"척수 한 토막":"뇌척수액 푸른 안료",c:"#3a82d7"},{f:"solvent",n:"오렌지 용제",c:"#e66d28"},{f:"clue",n:"유진의 붉은 머리끈",c:"#a61236"}];const canCraft=flags.includes("red")&&flags.includes("yellow")&&!flags.includes("solvent");return <div className={`absolute inset-4 z-50 overflow-auto border-2 bg-[#101425]/95 p-6 sm:inset-8 ${low?"border-red-500 glitch":"border-[#d9cbaa]"}`}><div className="flex justify-between"><div><h2 className="text-lg font-black tracking-widest">가방 / INVENTORY</h2><p className="mt-1 text-[10px] text-slate-400">일기 {['note','diary2','diary3','diary4'].filter(d=>flags.includes(d as Flag)).length}/4</p></div><button onClick={close}>✕</button></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{items.map(i=><div key={i.f} className={`border border-white/15 p-4 ${flags.includes(i.f as Flag)?"":"opacity-20"}`}><div className="mb-3 h-10 w-10 border-4 border-black/25" style={{background:i.c}}/><p className="text-xs">{i.n}</p></div>)}</div><button disabled={!canCraft} onClick={craft} className="mt-5 w-full border border-orange-400 p-3 text-sm text-orange-200 enabled:bg-orange-500/20 disabled:opacity-25">붉은 안료 + 노란 안료 → 오렌지 용제 조합</button></div>}
function MixingPuzzle({close,complete}:{close:()=>void;complete:()=>void}){const [rgb,setRgb]=useState([80,80,80]);const target=[212,143,56];const ok=rgb.every((v,i)=>Math.abs(v-target[i])<=8);const colors=["R 동맥의 붉은색","G 담즙의 노란색","B 뇌척수액의 푸른색"];return <div className="absolute inset-4 z-50 overflow-auto border-2 border-amber-300 bg-[#0d1020]/97 p-5 sm:inset-10"><div className="flex justify-between"><div><p className="text-[10px] tracking-[.3em] text-amber-300">B1F · RGB HUMAN PIGMENT</p><h2 className="mt-1 text-lg font-black">인체 물감 배합기</h2></div><button onClick={close}>✕</button></div><p className="mt-4 text-xs text-slate-400">연구 일지의 목표값 R212 · G143 · B56에 맞춰 각 안료 밸브를 조절하세요. ±8 허용</p><div className="mt-5 grid gap-4">{rgb.map((v,i)=><label key={colors[i]} className="grid grid-cols-[150px_1fr_42px] items-center gap-3 text-xs"><span>{colors[i]}</span><input aria-label={colors[i]} type="range" min="0" max="255" value={v} onChange={e=>setRgb(a=>a.map((n,j)=>j===i?Number(e.target.value):n))} className="accent-rose-500"/><b>{v}</b></label>)}</div><div className="mt-6 flex items-center gap-4"><div className="h-14 flex-1 border-4 border-black/30" style={{background:`rgb(${rgb.join(",")})`}}/><button disabled={!ok} onClick={complete} className="border border-amber-300 px-5 py-4 text-sm font-black enabled:bg-amber-300 enabled:text-black disabled:opacity-30">배합 확정</button></div></div>}
function HideQTE({done}:{done:(success:boolean)=>void}){const [breath,setBreath]=useState(50),breathRef=useRef(50);const [time,setTime]=useState(5);const adjust=useCallback((amount:number)=>setBreath(v=>{const n=Math.max(0,Math.min(100,v+amount));breathRef.current=n;return n}),[]);useEffect(()=>{const press=(e:KeyboardEvent)=>{if(e.code==="Space"){e.preventDefault();adjust(-12)}};addEventListener("keydown",press);const drift=setInterval(()=>adjust((Math.random()-.47)*24),250);const clock=setInterval(()=>setTime(v=>{if(v<=1){clearInterval(clock);clearInterval(drift);setTimeout(()=>done(breathRef.current>25&&breathRef.current<75),0);return 0}return v-1}),1000);return()=>{removeEventListener("keydown",press);clearInterval(drift);clearInterval(clock)}},[adjust,done]);return <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/90 p-6"><div className="w-full max-w-md text-center"><p className="text-xs tracking-[.4em] text-red-400">B2F 캐비닛 · 숨을 참아</p><h2 className="mt-3 text-2xl font-black">클렘에게 심장 소리를 들키지 마세요</h2><p className="mt-2 text-sm text-slate-400">Space 또는 버튼으로 바늘을 안전 영역에 유지 · {time}초</p><div className="relative mt-8 h-7 border border-white/30 bg-white/5"><div className="absolute inset-y-0 left-1/4 w-1/2 bg-emerald-500/25"/><div className="absolute inset-y-0 w-1 bg-white transition-all" style={{left:`${breath}%`}}/></div><button onClick={()=>adjust(-12)} className="mt-7 rounded-full border-2 border-white/40 px-9 py-4 font-black active:bg-white active:text-black">SPACE · 호흡 억제</button></div></div>}
function Pause({save,close,quit}:{save:()=>void;close:()=>void;quit:()=>void}){return <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/75"><div className="w-64 border-2 border-white/40 bg-[#111426] p-6 text-center"><h2 className="mb-5 text-xl font-black tracking-widest">PAUSED</h2><button onClick={close} className="mb-2 block w-full border border-white/20 p-2">계속하기</button><button onClick={save} className="mb-2 block w-full border border-amber-400/50 p-2 text-amber-300">게임 저장</button><button onClick={quit} className="block w-full border border-rose-400/50 p-2 text-rose-300">타이틀로</button></div></div>}
function Dpad({move}:{move:(d:Dir,on:boolean)=>void}){const B=({d,s}:{d:Dir,s:string})=><button aria-label={d} onPointerDown={()=>move(d,true)} onPointerUp={()=>move(d,false)} onPointerCancel={()=>move(d,false)} className="h-9 w-9 border border-white/25 bg-white/10">{s}</button>;return <div className="grid grid-cols-3"><i/><B d="up" s="▲"/><i/><B d="left" s="◀"/><B d="down" s="▼"/><B d="right" s="▶"/></div>}
function Ending({kind,onAgain}:{kind:"normal"|"bad"|"true";onAgain:()=>void}){const data=kind==="true"?{tag:"TRUE ENDING",title:"무지개의 진실",text:"유진의 머리끈이 원장의 거짓말을 무너뜨렸다. 유나는 일곱 안료에 갇힌 아이들의 기억을 해방한다.",bg:"bg-[#071912]",color:"text-emerald-300"}:kind==="normal"?{tag:"NORMAL ENDING",title:"잿더미 속 탈출",text:"유나는 학원을 빠져나왔지만, 유진의 진실은 아직 지하에 남아 있다.",bg:"bg-[#0a1220]",color:"text-amber-300"}:{tag:"BAD ENDING",title:"영원한 물감",text:"광기가 유나의 이름을 지웠다. 원장의 캔버스에 새로운 푸른색이 더해졌다.",bg:"bg-[#180308]",color:"text-red-500"};return <main className={`flex min-h-screen items-center justify-center p-6 text-center ${data.bg}`}><div><p className={`text-xs tracking-[.5em] ${data.color}`}>{data.tag}</p><h1 className="mt-5 text-4xl font-black sm:text-6xl">{data.title}</h1><p className="mx-auto mt-6 max-w-lg leading-8 text-slate-400">{data.text}</p><button onClick={onAgain} className="mt-10 border border-white/30 px-8 py-3 hover:bg-white/10">처음부터 다시</button></div></main>}
