/* eslint-disable react-hooks/immutability, react-hooks/static-components, react-hooks/exhaustive-deps */
"use client";

import { useCallback, useEffect, useRef, useState } from "react";

type Scene = "title" | "game" | "ending";
type Dir = "up" | "down" | "left" | "right";
type Flag = "note" | "red" | "puzzle" | "clue" | "chase";
type SaveData = { x:number; y:number; flags:Flag[]; chapter:number; sanity?:number };

const W=768, H=432;
const SAVE_KEY="rainbow-atelier-save-v1";
const dialogues: Record<string,string[]> = {
  intro:["유나: 오늘도 원장님 수업은 참 따뜻해.","…그런데, 복도에서 기름 냄새가 나.","[조작] 방향키/WASD 이동 · Z/Space 조사 · Shift 달리기"],
  note:["『아이들이 두려움은 정맥의 푸른빛을 더욱 깊게 만든다.』","유나: 이건… 원장님의 글씨야."],
  locked:["지하 문이다. 세 개의 안료 홈이 비어 있다.","붉은색 물감을 먼저 찾아야 할 것 같다."],
  red:["동맥의 붉은색 물감 튜브를 얻었다.","손끝에 닿자 미지근한 맥박이 느껴진다."],
  puzzle:["R · G · B 안료가 하나의 회색으로 가라앉는다.","철컥. 지하 2층으로 향하는 문이 열렸다."],
  clue:["낡은 작업대 아래에서 붉은 머리끈을 발견했다.","유나: 유진이 거야… 동생은 분명 여기까지 왔었어.","[TRUE CLUE] 엔딩의 진실에 한 걸음 가까워졌다."],
  minhyuk:["민혁: 유나야… 손에 왜 그래? 피가… 피가 안 멈추잖아!","유나: 선배, 이건 피가 아니라 ‘황금빛 노란색’이야.","민혁: 다음은 네 차례야. 네 안에는 아주 깊은 푸른 슬픔이 있거든…"],
  escape:["차가운 새벽 공기가 폐 안으로 들어온다.","하지만 학원 지하에서는 아직도 붓 긁는 소리가 난다."],
};

function useAudio(){
  const ctx=useRef<AudioContext|null>(null);
  return useCallback((kind:"step"|"pickup"|"shock")=>{
    try { const C=window.AudioContext || (window as typeof window & {webkitAudioContext:typeof AudioContext}).webkitAudioContext; const c=ctx.current??new C(); ctx.current=c; const o=c.createOscillator(), g=c.createGain(); o.connect(g);g.connect(c.destination); const now=c.currentTime; o.type=kind==="shock"?"sawtooth":"square"; o.frequency.setValueAtTime(kind==="step"?90:kind==="pickup"?480:55,now); if(kind==="shock")o.frequency.exponentialRampToValueAtTime(620,now+.35); g.gain.setValueAtTime(.05,now);g.gain.exponentialRampToValueAtTime(.001,now+(kind==="shock"?.45:.08));o.start(now);o.stop(now+(kind==="shock"?.46:.09)); } catch {}
  },[]);
}

export default function RainbowAtelier(){
  const canvas=useRef<HTMLCanvasElement>(null); const keys=useRef(new Set<string>()); const player=useRef({x:102,y:306,dir:"down" as Dir}); const enemy=useRef({x:650,y:90});
  const [scene,setScene]=useState<Scene>("title"),[dialog,setDialog]=useState<string[]>([]),[line,setLine]=useState(0),[flags,setFlags]=useState<Flag[]>([]),[chapter,setChapter]=useState(1),[stamina,setStamina]=useState(100),[sanity,setSanity]=useState(100),[light,setLight]=useState(true),[inventory,setInventory]=useState(false),[paused,setPaused]=useState(false),[mixing,setMixing]=useState(false),[hiding,setHiding]=useState(false),[flash,setFlash]=useState(false),[hasSave,setHasSave]=useState(()=>typeof window!=="undefined"&&!!localStorage.getItem(SAVE_KEY)),[ending,setEnding]=useState<"normal"|"bad"|"true">("normal");
  const beep=useAudio(); const flagsRef=useRef(flags); const dialogRef=useRef(dialog); const staminaRef=useRef(stamina); const sanityRef=useRef(sanity); const chapterRef=useRef(chapter); const last=useRef(0);
  useEffect(()=>{flagsRef.current=flags},[flags]); useEffect(()=>{dialogRef.current=dialog},[dialog]);useEffect(()=>{staminaRef.current=stamina},[stamina]);useEffect(()=>{sanityRef.current=sanity},[sanity]);useEffect(()=>{chapterRef.current=chapter},[chapter]);
  const speak=useCallback((lines:string[])=>{setDialog(lines);setLine(0)},[]);
  const addFlag=useCallback((f:Flag)=>setFlags(v=>v.includes(f)?v:[...v,f]),[]);
  const save=useCallback(()=>{localStorage.setItem(SAVE_KEY,JSON.stringify({x:player.current.x,y:player.current.y,flags:flagsRef.current,chapter:chapterRef.current,sanity:sanityRef.current} satisfies SaveData));setHasSave(true);beep("pickup")},[beep]);
  const start=useCallback((load=false)=>{if(load){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY)||"") as SaveData;player.current.x=s.x;player.current.y=s.y;setFlags(s.flags);setChapter(s.chapter);setSanity(s.sanity??100)}catch{}} else {player.current={x:102,y:306,dir:"down"};setFlags([]);setChapter(1);setSanity(100);speak(dialogues.intro)} setScene("game")},[speak]);

  const interact=useCallback(()=>{
    if(dialogRef.current.length){if(line<dialogRef.current.length-1)setLine(v=>v+1);else setDialog([]);return}
    const {x,y}=player.current; const f=flagsRef.current;
    if(x<180&&y<150&&!f.includes("note")){addFlag("note");speak(dialogues.note);beep("pickup")}
    else if(x>585&&y<155&&!f.includes("red")){addFlag("red");speak(dialogues.red);beep("pickup")}
    else if(x>610&&y>285&&!f.includes("puzzle")){if(f.includes("red"))setMixing(true);else speak(dialogues.locked)}
    else if(x>585&&y<155&&f.includes("chase")){setHiding(true);beep("pickup")}
    else if(x>315&&x<388&&y<170&&f.includes("puzzle")&&!f.includes("clue")){addFlag("clue");speak(dialogues.clue);beep("pickup")}
    else if(x>=388&&x<490&&y<170&&f.includes("puzzle")&&!f.includes("chase")){addFlag("chase");setChapter(3);setSanity(v=>Math.max(0,v-28));setFlash(true);beep("shock");speak(dialogues.minhyuk);setTimeout(()=>setFlash(false),700)}
    else if(x<105&&y>300&&f.includes("chase")){setEnding(f.includes("clue")?"true":"normal");setScene("ending");speak(dialogues.escape)}
  },[addFlag,beep,line,speak]);

  useEffect(()=>{const down=(e:KeyboardEvent)=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();keys.current.add(e.key.toLowerCase());if(e.key===" "||e.key.toLowerCase()==="z")interact();if(e.key.toLowerCase()==="f")setLight(v=>!v);if(e.key.toLowerCase()==="i"||e.key==="Tab"){e.preventDefault();setInventory(v=>!v)}if(e.key==="Escape")setPaused(v=>!v)};const up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[interact]);

  useEffect(()=>{if(scene!=="game")return;let raf=0;const loop=(t:number)=>{const dt=Math.min((t-last.current)/16.67,2);last.current=t;const k=keys.current,p=player.current;const running=(k.has("shift"))&&staminaRef.current>0;const speed=(running?3.4:2.05)*dt;if(!paused&&!inventory&&!mixing&&!hiding&&!dialogRef.current.length){let dx=0,dy=0;if(k.has("arrowleft")||k.has("a")){dx=-speed;p.dir="left"}if(k.has("arrowright")||k.has("d")){dx=speed;p.dir="right"}if(k.has("arrowup")||k.has("w")){dy=-speed;p.dir="up"}if(k.has("arrowdown")||k.has("s")){dy=speed;p.dir="down"}p.x=Math.max(55,Math.min(W-48,p.x+dx));p.y=Math.max(62,Math.min(H-43,p.y+dy));setStamina(v=>Math.max(0,Math.min(100,v+(running&&(dx||dy)?-.45:.28)*dt)));if(flagsRef.current.includes("chase")){setSanity(v=>Math.max(0,v-.018*dt));const e=enemy.current,ang=Math.atan2(p.y-e.y,p.x-e.x);e.x+=Math.cos(ang)*1.35*dt;e.y+=Math.sin(ang)*1.35*dt;if(Math.hypot(p.x-e.x,p.y-e.y)<25||sanityRef.current<=0){setEnding("bad");setScene("ending");beep("shock")}}}draw();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[scene,paused,inventory,mixing,hiding,beep]);

  const draw=useCallback(()=>{const c=canvas.current;if(!c)return;const x=c.getContext("2d")!;x.imageSmoothingEnabled=false;const horror=flagsRef.current.includes("chase");x.fillStyle=horror?"#09050b":"#1a2030";x.fillRect(0,0,W,H);x.fillStyle=horror?"#211015":"#d6b67e";x.fillRect(36,42,W-72,H-74);for(let yy=56;yy<H-45;yy+=32)for(let xx=50;xx<W-50;xx+=32){x.fillStyle=(xx/32+yy/32)%2? (horror?"#3a1a20":"#debF89"):(horror?"#2c1319":"#c8a470");x.fillRect(xx,yy,29,29)}x.fillStyle="#443346";x.fillRect(36,36,W-72,24);x.fillRect(36,H-42,W-72,12);x.fillStyle="#6a3b3d";x.fillRect(286,76,196,75);x.fillStyle="#c99b5a";x.fillRect(304,91,50,44);x.fillRect(377,91,86,44);x.fillStyle="#263440";x.fillRect(50,78,125,72);x.fillStyle="#8a714b";for(let i=0;i<3;i++)x.fillRect(60+i*36,91,24,42);x.fillStyle="#342a40";x.fillRect(596,74,122,78);x.fillStyle="#a52d43";x.fillRect(610,91,92,13);x.fillStyle="#1e1722";x.fillRect(620,109,72,29);x.fillStyle="#222536";x.fillRect(614,278,104,100);x.fillStyle="#7d5b3e";x.fillRect(630,292,72,72);x.fillStyle="#ddb81d";x.fillRect(662,328,8,8);x.fillStyle="#1d2029";x.fillRect(36,282,24,95);x.fillStyle="#eee2c5";x.font="bold 12px monospace";x.fillText("EXIT",31,275);
    const p=player.current;x.fillStyle="#5c376c";x.fillRect(p.x-8,p.y-11,16,19);x.fillStyle="#dfb09c";x.fillRect(p.x-7,p.y-18,14,9);x.fillStyle="#322231";x.fillRect(p.x-8,p.y-20,16,5);x.fillStyle="#fff";x.fillRect(p.x-4,p.y-16,2,2);x.fillRect(p.x+3,p.y-16,2,2);x.fillStyle="#28203a";x.fillRect(p.x-8,p.y+8,6,6);x.fillRect(p.x+2,p.y+8,6,6);
    if(horror){const e=enemy.current;x.fillStyle="#19111b";x.fillRect(e.x-11,e.y-15,22,28);x.fillStyle="#e3d2c4";x.fillRect(e.x-9,e.y-23,18,12);x.fillStyle="#d91f3c";x.fillRect(e.x-5,e.y-19,3,3);x.fillRect(e.x+3,e.y-19,3,3);x.fillStyle="rgba(160,0,20,.15)";x.fillRect(0,0,W,H)}
    if(light&&!horror){const g=x.createRadialGradient(p.x,p.y,25,p.x,p.y,135);g.addColorStop(0,"rgba(255,244,192,.17)");g.addColorStop(1,"rgba(0,0,0,.7)");x.fillStyle=g;x.fillRect(0,0,W,H)}else if(!light){x.fillStyle="rgba(0,0,0,.72)";x.fillRect(0,0,W,H)}
  },[light]);

  const moveTouch=(d:Dir,on:boolean)=>{const key={up:"w",down:"s",left:"a",right:"d"}[d];if(on)keys.current.add(key);else keys.current.delete(key)};
  if(scene==="title")return <TitleScreen onStart={()=>start(false)} onLoad={()=>start(true)} hasSave={hasSave}/>;
  if(scene==="ending")return <Ending kind={ending} onAgain={()=>{enemy.current={x:650,y:90};start(false)}}/>;
  const objective=!flags.includes("note")?"1F · 원장실 기록 조사":!flags.includes("red")?"B1F · 붉은 안료 찾기":!flags.includes("puzzle")?"B1F · RGB 배합으로 문 열기":!flags.includes("chase")?"B3F · 왼쪽 작업대 단서 / 오른쪽 계단":"원장을 피해 1F 출구로 도망쳐!";
  const distorted=sanity<40;
  return <main className={`min-h-screen bg-[#090b17] px-3 py-5 lg:px-8 ${distorted?"glitch":""}`}><div className="mx-auto max-w-[1180px]"><header className="mb-4 flex items-end justify-between gap-4"><div><p className="text-[10px] tracking-[.35em] text-rose-400">THE RAINBOW ATELIER</p><h1 className="mt-1 text-xl font-black sm:text-2xl">무지개빛 미술학원</h1></div><div className="text-right text-xs text-slate-400">CHAPTER {chapter} · {chapter===1?"1F / B1F":chapter===2?"B3F":"B3F → 1F"}<br/><span className="text-amber-300">{distorted?"누가 내 붓으로 너를 그리고 있어…":objective}</span></div></header><section className={`relative overflow-hidden border-4 border-[#272b42] bg-black shadow-2xl crt ${flash?"glitch":""}`}><canvas ref={canvas} width={W} height={H} className="pixel block aspect-video w-full" aria-label="무지개빛 미술학원 게임 화면"/><div className="absolute left-3 top-3 z-20 flex gap-2"><Hud label="STAMINA" value={stamina}/><Hud label="SANITY" value={sanity} danger/><button onClick={()=>setLight(v=>!v)} className="border border-white/20 bg-black/65 px-2 text-xs">{light?"◉ LIGHT":"○ DARK"}</button></div>{flags.includes("chase")&&<div className="pointer-events-none absolute inset-x-0 top-4 z-20 text-center text-sm font-black tracking-[.35em] text-red-500">RUN · 캐비닛에서 숨을 수 있다</div>}{dialog.length>0&&<button onClick={interact} className="absolute inset-x-4 bottom-4 z-40 min-h-24 border-2 border-[#e9d9b8] bg-[#0e1020]/95 p-4 text-left text-sm leading-7 shadow-[6px_6px_0_#111] sm:text-base"><span>{dialog[line]}</span><span className="float absolute bottom-2 right-3 text-amber-300">▼</span></button>}{inventory&&<Inventory flags={flags} close={()=>setInventory(false)}/>} {mixing&&<MixingPuzzle close={()=>setMixing(false)} complete={()=>{setMixing(false);addFlag("puzzle");setChapter(2);speak(dialogues.puzzle);beep("pickup")}}/>}{hiding&&<HideQTE done={(success)=>{setHiding(false);if(success){enemy.current={x:650,y:90};setSanity(v=>Math.min(100,v+12))}else{setSanity(v=>Math.max(0,v-25));beep("shock")}}}/>}{paused&&<Pause save={save} close={()=>setPaused(false)} quit={()=>setScene("title")}/>}</section><footer className="mt-4 grid gap-3 text-xs text-slate-400 md:grid-cols-[1fr_auto]"><p>방향키 / WASD 이동 · Shift 달리기 · Z / Space 조사 · F 손전등 · I / Tab 가방 · ESC 메뉴</p><div className="flex items-center justify-center gap-2 md:hidden"><Dpad move={moveTouch}/><button onPointerDown={interact} className="h-14 w-14 rounded-full border-2 border-rose-400 bg-rose-500/20 font-black text-rose-200">Z</button></div><p className="text-right text-slate-600">ESC 메뉴에서 저장 · 광기 0% 시 BAD ENDING</p></footer></div></main>
}

function Hud({label,value,danger=false}:{label:string,value:number;danger?:boolean}){return <div className="w-24 border border-white/20 bg-black/65 p-1 sm:w-28"><div className="mb-1 text-[8px] tracking-widest">{label} {Math.round(value)}</div><div className="h-1.5 bg-white/10"><div className={`h-full transition-all ${danger&&value<40?"bg-red-500":"bg-amber-300"}`} style={{width:`${value}%`}}/></div></div>}
function TitleScreen({onStart,onLoad,hasSave}:{onStart:()=>void;onLoad:()=>void;hasSave:boolean}){return <main className="noise relative flex min-h-screen items-center justify-center overflow-hidden bg-[radial-gradient(circle_at_50%_35%,#35224c_0,#111326_45%,#060812_100%)] p-6"><div className="absolute -left-20 top-16 h-52 w-52 rotate-12 rounded-full bg-rose-500/10 blur-3xl"/><div className="relative z-10 w-full max-w-3xl text-center"><div className="mx-auto mb-8 grid h-24 w-24 rotate-3 grid-cols-3 gap-1 border-4 border-[#f3e6c9] bg-[#eee0c1] p-3 shadow-[10px_10px_0_#57182c]"><i className="bg-red-500"/><i className="bg-amber-300"/><i className="bg-emerald-400"/><i className="bg-cyan-400"/><i className="bg-blue-500"/><i className="bg-violet-500"/><i className="bg-fuchsia-400"/><i className="bg-rose-300"/><i className="bg-slate-900"/></div><p className="mb-3 text-xs tracking-[.55em] text-rose-400">2D PIXEL PSYCHOLOGICAL HORROR</p><h1 className="text-4xl font-black tracking-[-.06em] text-[#fff4d9] drop-shadow-[5px_5px_0_#7e1733] sm:text-7xl">무지개빛<br/>미술학원</h1><p className="mt-4 font-serif text-sm tracking-[.18em] text-slate-400">The Rainbow Atelier</p><p className="mx-auto mt-8 max-w-md text-sm leading-7 text-slate-300">사라진 동생, 일곱 가지 물감, 그리고 밤마다 들리는 젖은 붓 소리.<br/><span className="text-rose-300">예쁜 색은 언제나 좋은 기억에서 만들어질까?</span></p><div className="mt-10 flex flex-col items-center gap-3"><button onClick={onStart} className="pulse-red w-56 border-2 border-rose-400 bg-rose-600 px-7 py-3 font-black tracking-[.25em] hover:bg-rose-500">새 게임</button><button disabled={!hasSave} onClick={onLoad} className="w-56 border border-white/20 bg-white/5 px-7 py-3 text-sm tracking-[.2em] enabled:hover:bg-white/10 disabled:opacity-30">이어하기</button></div></div><span className="absolute bottom-4 text-[10px] tracking-widest text-slate-600">HEADPHONES RECOMMENDED · 만 15세 이상 권장</span></main>}
function Inventory({flags,close}:{flags:Flag[];close:()=>void}){const items=[{f:"note",n:"원장의 연구 일지 #3",c:"#b7b0a0"},{f:"red",n:"핏빛 붉은 안료",c:"#d72e49"},{f:"puzzle",n:"회색 혼합 안료",c:"#777b88"},{f:"clue",n:"유진의 붉은 머리끈",c:"#a61236"}];return <div className="absolute inset-4 z-50 overflow-auto border-2 border-[#d9cbaa] bg-[#101425]/95 p-6 sm:inset-8"><div className="flex justify-between"><h2 className="text-lg font-black tracking-widest">가방 / INVENTORY</h2><button onClick={close}>✕</button></div><div className="mt-6 grid gap-3 sm:grid-cols-4">{items.map(i=><div key={i.f} className={`border border-white/15 p-4 ${flags.includes(i.f as Flag)?"":"opacity-20"}`}><div className="mb-3 h-10 w-10 border-4 border-black/25" style={{background:i.c}}/><p className="text-xs">{i.n}</p></div>)}</div></div>}
function MixingPuzzle({close,complete}:{close:()=>void;complete:()=>void}){const [rgb,setRgb]=useState([80,80,80]);const target=[212,143,56];const ok=rgb.every((v,i)=>Math.abs(v-target[i])<=8);const colors=["R 동맥의 붉은색","G 담즙의 노란색","B 뇌척수액의 푸른색"];return <div className="absolute inset-4 z-50 overflow-auto border-2 border-amber-300 bg-[#0d1020]/97 p-5 sm:inset-10"><div className="flex justify-between"><div><p className="text-[10px] tracking-[.3em] text-amber-300">B1F · RGB HUMAN PIGMENT</p><h2 className="mt-1 text-lg font-black">인체 물감 배합기</h2></div><button onClick={close}>✕</button></div><p className="mt-4 text-xs text-slate-400">연구 일지의 목표값 R212 · G143 · B56에 맞춰 각 안료 밸브를 조절하세요. ±8 허용</p><div className="mt-5 grid gap-4">{rgb.map((v,i)=><label key={colors[i]} className="grid grid-cols-[150px_1fr_42px] items-center gap-3 text-xs"><span>{colors[i]}</span><input aria-label={colors[i]} type="range" min="0" max="255" value={v} onChange={e=>setRgb(a=>a.map((n,j)=>j===i?Number(e.target.value):n))} className="accent-rose-500"/><b>{v}</b></label>)}</div><div className="mt-6 flex items-center gap-4"><div className="h-14 flex-1 border-4 border-black/30" style={{background:`rgb(${rgb.join(",")})`}}/><button disabled={!ok} onClick={complete} className="border border-amber-300 px-5 py-4 text-sm font-black enabled:bg-amber-300 enabled:text-black disabled:opacity-30">배합 확정</button></div></div>}
function HideQTE({done}:{done:(success:boolean)=>void}){const [breath,setBreath]=useState(50);const [time,setTime]=useState(5);useEffect(()=>{const drift=setInterval(()=>setBreath(v=>Math.max(0,Math.min(100,v+(Math.random()-.47)*24))),250);const clock=setInterval(()=>setTime(v=>{if(v<=1){clearInterval(clock);clearInterval(drift);setTimeout(()=>done(breath>25&&breath<75),0);return 0}return v-1}),1000);return()=>{clearInterval(drift);clearInterval(clock)}},[]);return <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/90 p-6"><div className="w-full max-w-md text-center"><p className="text-xs tracking-[.4em] text-red-400">캐비닛 안 · 숨을 참아</p><h2 className="mt-3 text-2xl font-black">심장 소리를 들키지 마세요</h2><p className="mt-2 text-sm text-slate-400">버튼을 눌러 바늘을 안전 영역에 유지 · {time}초</p><div className="relative mt-8 h-7 border border-white/30 bg-white/5"><div className="absolute inset-y-0 left-1/4 w-1/2 bg-emerald-500/25"/><div className="absolute inset-y-0 w-1 bg-white transition-all" style={{left:`${breath}%`}}/></div><button onClick={()=>setBreath(v=>Math.max(0,v-12))} className="mt-7 rounded-full border-2 border-white/40 px-9 py-4 font-black active:bg-white active:text-black">SPACE · 호흡 억제</button></div></div>}
function Pause({save,close,quit}:{save:()=>void;close:()=>void;quit:()=>void}){return <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/75"><div className="w-64 border-2 border-white/40 bg-[#111426] p-6 text-center"><h2 className="mb-5 text-xl font-black tracking-widest">PAUSED</h2><button onClick={close} className="mb-2 block w-full border border-white/20 p-2">계속하기</button><button onClick={save} className="mb-2 block w-full border border-amber-400/50 p-2 text-amber-300">게임 저장</button><button onClick={quit} className="block w-full border border-rose-400/50 p-2 text-rose-300">타이틀로</button></div></div>}
function Dpad({move}:{move:(d:Dir,on:boolean)=>void}){const B=({d,s}:{d:Dir,s:string})=><button aria-label={d} onPointerDown={()=>move(d,true)} onPointerUp={()=>move(d,false)} onPointerCancel={()=>move(d,false)} className="h-9 w-9 border border-white/25 bg-white/10">{s}</button>;return <div className="grid grid-cols-3"><i/><B d="up" s="▲"/><i/><B d="left" s="◀"/><B d="down" s="▼"/><B d="right" s="▶"/></div>}
function Ending({kind,onAgain}:{kind:"normal"|"bad"|"true";onAgain:()=>void}){const data=kind==="true"?{tag:"TRUE ENDING",title:"무지개의 진실",text:"유진의 머리끈이 원장의 거짓말을 무너뜨렸다. 유나는 일곱 안료에 갇힌 아이들의 기억을 해방한다.",bg:"bg-[#071912]",color:"text-emerald-300"}:kind==="normal"?{tag:"NORMAL ENDING",title:"잿더미 속 탈출",text:"유나는 학원을 빠져나왔지만, 유진의 진실은 아직 지하에 남아 있다.",bg:"bg-[#0a1220]",color:"text-amber-300"}:{tag:"BAD ENDING",title:"영원한 물감",text:"광기가 유나의 이름을 지웠다. 원장의 캔버스에 새로운 푸른색이 더해졌다.",bg:"bg-[#180308]",color:"text-red-500"};return <main className={`flex min-h-screen items-center justify-center p-6 text-center ${data.bg}`}><div><p className={`text-xs tracking-[.5em] ${data.color}`}>{data.tag}</p><h1 className="mt-5 text-4xl font-black sm:text-6xl">{data.title}</h1><p className="mx-auto mt-6 max-w-lg leading-8 text-slate-400">{data.text}</p><button onClick={onAgain} className="mt-10 border border-white/30 px-8 py-3 hover:bg-white/10">처음부터 다시</button></div></main>}
